# Generated by Django 5.0.2 on 2024-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='userimg/'),
        ),
    ]
